# Generated by Django 5.2.8 on 2026-03-06 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
            ],
        ),
    ]
